name: Auto Chartink Update

on:
  schedule:
    - cron: '0 10 * * 1-5'   # 3:30 PM IST
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install libraries
      run: pip install pandas openpyxl lxml requests

    - name: Run script
      run: python fetch_chartink.py

    - name: Commit updated excel
      run: |
        git config --global user.name "bot"
        git config --global user.email "bot@github.com"
        git add .
        git commit -m "Daily auto update"
        git push
